name: pre-commit validate-scopes

on:
  pull_request:
  push:
    paths:
      - scopes/
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      SCHEMA_URL: datasets/
    steps:
      - uses: actions/checkout@v2
        with:
          fetch_depth: 0
      - name: "Fetch master branch"  # So we can diff against it.
        run: |
          git fetch origin master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'
      - uses: pre-commit/action@v2.0.3
        with:
          extra_args: validate-scopes
