name: pre-commit validate-scopes
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
  push:
    paths:
      - scopes/
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      SCHEMA_URL: datasets/
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Fetch master branch"  # So we can diff against it.
        run: |
          git fetch origin master
      - id: changed-scopes
        # We are only interested in changed and new (not deleted) scopes files.
        run: echo "::set-output name=SCOPE_FILES::$(git diff --name-only --diff-filter=d origin/master.. -- scopes)"
        shell: bash
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.x'
      - uses: pre-commit/action@v3.0.1
        if: ${{ steps.changed-scopes.outputs.SCOPE_FILES != '' }}
        with:
          extra_args: validate-scopes
