name: validate-datasets
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
  push:
    paths:
      - datasets/
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Fetch master branch"  # So we can diff against it.
        run: |
          git fetch origin master
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - id: install-schema-tools
        run: |
          python -m pip install --force-reinstall -v "amsterdam-schema-tools>=8.3.0"
      - id: generate-previous-datasets
        run: |
          changed_paths=$(./scripts/generate_previous_datasets_from_master.sh ${{github.head_ref || github.ref_name}} | tail -n 1)
          echo "changed_paths=$changed_paths" >> $GITHUB_OUTPUT
      - id: validate-datasets
        run: |
          schema validate-datasets ${{steps.generate-previous-datasets.outputs.changed_paths}}
